language: go
go:
  - 1.3.1

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
  - go get github.com/fall2021-csc510-group40/Project-1/core/...

before_script:
  - cd core

script:
   - cd core  
   - go build core
   - go test -v ./...