language: go
go:
  - 1.17

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
  - git clone https://github.com/fall2021-csc510-group40/Project-1.git

script:
   - cd Project-1/core
   - go build
   - go test -v ./...